apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-imagerelease-operator-leader-election-role
  namespace: kube-imagerelease-operator-system
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
