---
apiVersion: kube-imagerelease-operator.nix.re/v1alpha1
kind: ImageRelease
metadata:
  name: hello-world
  namespace: default
spec:
  image: ghcr.io/example/hello-world@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
