// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver into out. in must be non-nil.
func (in *ImagePolicyReference) DeepCopyInto(out *ImagePolicyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePolicyReference.
func (in *ImagePolicyReference) DeepCopy() *ImagePolicyReference {
	if in == nil {
		return nil
	}
	out := new(ImagePolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver into out. in must be non-nil.
func (in *ImageRelease) DeepCopyInto(out *ImageRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRelease.
func (in *ImageRelease) DeepCopy() *ImageRelease {
	if in == nil {
		return nil
	}
	out := new(ImageRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver into out. in must be non-nil.
func (in *ImageReleaseList) DeepCopyInto(out *ImageReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImageRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageReleaseList.
func (in *ImageReleaseList) DeepCopy() *ImageReleaseList {
	if in == nil {
		return nil
	}
	out := new(ImageReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver into out. in must be non-nil.
func (in *ImageReleaseSpec) DeepCopyInto(out *ImageReleaseSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.ImagePolicyRef != nil {
		in, out := &in.ImagePolicyRef, &out.ImagePolicyRef
		*out = new(ImagePolicyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageReleaseSpec.
func (in *ImageReleaseSpec) DeepCopy() *ImageReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(ImageReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver into out. in must be non-nil.
func (in *ImageReleaseStatus) DeepCopyInto(out *ImageReleaseStatus) {
	*out = *in
	if in.ResolvedImage != nil {
		in, out := &in.ResolvedImage, &out.ResolvedImage
		*out = new(ResolvedImage)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.Workloads != nil {
		in, out := &in.Workloads, &out.Workloads
		*out = make([]WorkloadStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageReleaseStatus.
func (in *ImageReleaseStatus) DeepCopy() *ImageReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(ImageReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver into out. in must be non-nil.
func (in *ResolvedImage) DeepCopyInto(out *ResolvedImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedImage.
func (in *ResolvedImage) DeepCopy() *ResolvedImage {
	if in == nil {
		return nil
	}
	out := new(ResolvedImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver into out. in must be non-nil.
func (in *WorkloadStatus) DeepCopyInto(out *WorkloadStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadStatus.
func (in *WorkloadStatus) DeepCopy() *WorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadStatus)
	in.DeepCopyInto(out)
	return out
}
